spring.application.name=TallerIntegrador

# =========================
# POSTGRESQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/colegio_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# MONGODB
# =========================
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/colegio_mongo

# Aquí pones tu clave real
GOOGLE_PRIVATE_API_KEY=${GOOGLE_API_KEY}