spring.application.name=TallerIntegrador

server.servlet.context-path=/api

# =========================
# DEBUG & LOGGING
# =========================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# =========================
# POSTGRESQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/colegio_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data-test.sql
spring.jpa.defer-datasource-initialization=true

# =========================
# MULTIPART / FILE UPLOADS
# =========================
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# =========================
# MONGODB
# =========================
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/colegio_mongo

GOOGLE_PRIVATE_API_KEY=${GOOGLE_API_KEY}

jwt.secret=${JWT_SECRET_KEY}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

app.dominio-institucional=@semantika.edu.pe